version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9
      - image: circleci/mongo:3.4-ram
    environment:
      - MONGODB_URI: "mongodb://localhost:27017/checkin"
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run: 
          name: Install NPM
          command: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: React Test Suite
          command: ./node_modules/.bin/gulp test
      - run:
          name: Compile Server Test
          command: npm run test-server
      - run:
          name: Migrate DB
          command: npm run migrate

  deploy:
    docker:
      - image: circleci/node:8.9
    environment:
      HEROKU_APP_NAME: tesc-checkin
    steps:
      - checkout
      - run:
          name: Run Setup Script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "d9:05:a8:9c:0c:23:0d:96:54:c7:8e:80:80:8d:cc:57"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
  
  docs-build:
    docker:
      - image: circleci/node:11.4
    steps:
      - checkout
      - run: 
          name: Install NPM
          command: npm install
      - run:
          name: Build Server Documentation
          command: npm run gen-server-docs
      - persist_to_workspace:
          root: ~/
          paths: ./project/docs/server

  docs-deploy:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout 
      - attach_workspace:
          at: ~/
      - run:
          name: Install and configure deps
          command: |
            npm install gh-pages@2.0.1
            git config user.email "ci-build@tesc.ucsd.edu"
            git config user.name "ci-build"
      - run:
          name: debug
          command: |
            ls
            echo $HOME $(pwd)
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dist ~/docs
    
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
  docs:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: 
                - master
                - server-docs